<link href="${ctx_bootstrap}/css/font-awesome.min.css?v=4.4.0" rel="stylesheet">
<link href="${ctx_bootstrap}/css/icon.css" rel="stylesheet">
<div id="icon_li" class="main">
	<ul class="icon_lists clear">
		<li><i id="fa fa-glass" class="fa fa-glass icon iconfont"></i></li>
		<li><i id="fa fa-music" class="fa fa-music icon iconfont"></i></li>
		<li><i id="fa fa-search" class="fa fa-search icon iconfont"></i></li>
		<li><i id="fa fa-envelope-o" class="fa fa-envelope-o icon iconfont"></i></li>
		<li><i id="fa fa-heart" class="fa fa-heart icon iconfont"></i></li>
		<li><i id="fa fa-star" class="fa fa-star icon iconfont"></i></li>
		<li><i id="fa fa-star-o" class="fa fa-star-o icon iconfont"></i></li>
		<li><i id="fa fa-user" class="fa fa-user icon iconfont"></i></li>
		<li><i id="fa fa-film" class="fa fa-film icon iconfont"></i></li>
		<li><i id="fa fa-th-large" class="fa fa-th-large icon iconfont"></i></li>
		<li><i id="fa fa-th" class="fa fa-th icon iconfont"></i></li>
		<li><i id="fa fa-th-list" class="fa fa-th-list icon iconfont"></i></li>
		<li><i id="fa fa-check" class="fa fa-check icon iconfont"></i></li>
		<li><i id="fa fa-search-plus" class="fa fa-search-plus icon iconfont"></i></li>
		<li><i id="fa fa-search-minus" class="fa fa-search-minus icon iconfont"></i></li>
		<li><i id="fa fa-power-off" class="fa fa-power-off icon iconfont"></i></li>
		<li><i id="fa fa-signal" class="fa fa-signal icon iconfont"></i></li>
		<li><i id="fa fa-trash-o" class="fa fa-trash-o icon iconfont"></i></li>
		<li><i id="fa fa-home" class="fa fa-home icon iconfont"></i></li>
		<li><i id="fa fa-file-o" class="fa fa-file-o icon iconfont"></i></li>
		<li><i id="fa fa-clock-o" class="fa fa-clock-o icon iconfont"></i></li>
		<li><i id="fa fa-road" class="fa fa-road icon iconfont"></i></li>
		<li><i id="fa fa-download" class="fa fa-download icon iconfont"></i></li>
		<li><i id="fa fa-arrow-circle-o-down" class="fa fa-arrow-circle-o-down icon iconfont"></i></li>
		<li><i id="fa fa-arrow-circle-o-up" class="fa fa-arrow-circle-o-up icon iconfont"></i></li>
		<li><i id="fa fa-inbox" class="fa fa-inbox icon iconfont"></i></li>
		<li><i id="fa fa-play-circle-o" class="fa fa-play-circle-o icon iconfont"></i></li>
		<li><i id="fa fa-refresh" class="fa fa-refresh icon iconfont"></i></li>
		<li><i id="fa fa-list-alt" class="fa fa-list-alt icon iconfont"></i></li>
		<li><i id="fa fa-lock" class="fa fa-lock icon iconfont"></i></li>
		<li><i id="fa fa-flag" class="fa fa-flag icon iconfont"></i></li>
		<li><i id="fa fa-headphones" class="fa fa-headphones icon iconfont"></i></li>
		<li><i id="fa fa-volume-off" class="fa fa-volume-off icon iconfont"></i></li>
		<li><i id="fa fa-volume-down" class="fa fa-volume-down icon iconfont"></i></li>
		<li><i id="fa fa-volume-up" class="fa fa-volume-up icon iconfont"></i></li>
		<li><i id="fa fa-qrcode" class="fa fa-qrcode icon iconfont"></i></li>
		<li><i id="fa fa-barcode" class="fa fa-barcode icon iconfont"></i></li>
		<li><i id="fa fa-tag" class="fa fa-tag icon iconfont"></i></li>
		<li><i id="fa fa-tags" class="fa fa-tags icon iconfont"></i></li>
		<li><i id="fa fa-book" class="fa fa-book icon iconfont"></i></li>
		<li><i id="fa fa-bookmark" class="fa fa-bookmark icon iconfont"></i></li>
		<li><i id="fa fa-print" class="fa fa-print icon iconfont"></i></li>
		<li><i id="fa fa-camera" class="fa fa-camera icon iconfont"></i></li>
		<li><i id="fa fa-font" class="fa fa-font icon iconfont"></i></li>
		<li><i id="fa fa-bold" class="fa fa-bold icon iconfont"></i></li>
		<li><i id="fa fa-italic" class="fa fa-italic icon iconfont"></i></li>
		<li><i id="fa fa-text-height" class="fa fa-text-height icon iconfont"></i></li>
		<li><i id="fa fa-text-width" class="fa fa-text-width icon iconfont"></i></li>
		<li><i id="fa fa-align-left" class="fa fa-align-left icon iconfont"></i></li>
		<li><i id="fa fa-align-center" class="fa fa-align-center icon iconfont"></i></li>
		<li><i id="fa fa-align-right" class="fa fa-align-right icon iconfont"></i></li>
		<li><i id="fa fa-align-justify" class="fa fa-align-justify icon iconfont"></i></li>
		<li><i id="fa fa-list" class="fa fa-list icon iconfont"></i></li>
		<li><i id="fa fa-indent" class="fa fa-indent icon iconfont"></i></li>
		<li><i id="fa fa-video-camera" class="fa fa-video-camera icon iconfont"></i></li>
		<li><i id="fa fa-pencil" class="fa fa-pencil icon iconfont"></i></li>
		<li><i id="fa fa-map-marker" class="fa fa-map-marker icon iconfont"></i></li>
		<li><i id="fa fa-adjust" class="fa fa-adjust icon iconfont"></i></li>
		<li><i id="fa fa-tint" class="fa fa-tint icon iconfont"></i></li>
		<li><i id="fa fa-share-square-o" class="fa fa-share-square-o icon iconfont"></i></li>
		<li><i id="fa fa-check-square-o" class="fa fa-check-square-o icon iconfont"></i></li>
		<li><i id="fa fa-arrows" class="fa fa-arrows icon iconfont"></i></li>
		<li><i id="fa fa-step-backward" class="fa fa-step-backward icon iconfont"></i></li>
		<li><i id="fa fa-fast-backward" class="fa fa-fast-backward icon iconfont"></i></li>
		<li><i id="fa fa-backward" class="fa fa-backward icon iconfont"></i></li>
		<li><i id="fa fa-play" class="fa fa-play icon iconfont"></i></li>
		<li><i id="fa fa-pause" class="fa fa-pause icon iconfont"></i></li>
		<li><i id="fa fa-stop" class="fa fa-stop icon iconfont"></i></li>
		<li><i id="fa fa-forward" class="fa fa-forward icon iconfont"></i></li>
		<li><i id="fa fa-fast-forward" class="fa fa-fast-forward icon iconfont"></i></li>
		<li><i id="fa fa-step-forward" class="fa fa-step-forward icon iconfont"></i></li>
		<li><i id="fa fa-eject" class="fa fa-eject icon iconfont"></i></li>
		<li><i id="fa fa-chevron-left" class="fa fa-chevron-left icon iconfont"></i></li>
		<li><i id="fa fa-chevron-right" class="fa fa-chevron-right icon iconfont"></i></li>
		<li><i id="fa fa-plus-circle" class="fa fa-plus-circle icon iconfont"></i></li>
		<li><i id="fa fa-minus-circle" class="fa fa-minus-circle icon iconfont"></i></li>
		<li><i id="fa fa-times-circle" class="fa fa-times-circle icon iconfont"></i></li>
		<li><i id="fa fa-check-circle" class="fa fa-check-circle icon iconfont"></i></li>
		<li><i id="fa fa-question-circle" class="fa fa-question-circle icon iconfont"></i></li>
		<li><i id="fa fa-info-circle" class="fa fa-info-circle icon iconfont"></i></li>
		<li><i id="fa fa-crosshairs" class="fa fa-crosshairs icon iconfont"></i></li>
		<li><i id="fa fa-times-circle-o" class="fa fa-times-circle-o icon iconfont"></i></li>
		<li><i id="fa fa-check-circle-o" class="fa fa-check-circle-o icon iconfont"></i></li>
		<li><i id="fa fa-ban" class="fa fa-ban icon iconfont"></i></li>
		<li><i id="fa fa-arrow-left" class="fa fa-arrow-left icon iconfont"></i></li>
		<li><i id="fa fa-arrow-right" class="fa fa-arrow-right icon iconfont"></i></li>
		<li><i id="fa fa-arrow-up" class="fa fa-arrow-up icon iconfont"></i></li>
		<li><i id="fa fa-arrow-down" class="fa fa-arrow-down icon iconfont"></i></li>
		<li><i id="fa fa-expand" class="fa fa-expand icon iconfont"></i></li>
		<li><i id="fa fa-compress" class="fa fa-compress icon iconfont"></i></li>
		<li><i id="fa fa-plus" class="fa fa-plus icon iconfont"></i></li>
		<li><i id="fa fa-minus" class="fa fa-minus icon iconfont"></i></li>
		<li><i id="fa fa-asterisk" class="fa fa-asterisk icon iconfont"></i></li>
		<li><i id="fa fa-exclamation-circle" class="fa fa-exclamation-circle icon iconfont"></i></li>
		<li><i id="fa fa-gift" class="fa fa-gift icon iconfont"></i></li>
		<li><i id="fa fa-leaf" class="fa fa-leaf icon iconfont"></i></li>
		<li><i id="fa fa-fire" class="fa fa-fire icon iconfont"></i></li>
		<li><i id="fa fa-eye" class="fa fa-eye icon iconfont"></i></li>
		<li><i id="fa fa-eye-slash" class="fa fa-eye-slash icon iconfont"></i></li>
		<li><i id="fa fa-plane" class="fa fa-plane icon iconfont"></i></li>
		<li><i id="fa fa-calendar" class="fa fa-calendar icon iconfont"></i></li>
		<li><i id="fa fa-random" class="fa fa-random icon iconfont"></i></li>
		<li><i id="fa fa-comment" class="fa fa-comment icon iconfont"></i></li>
		<li><i id="fa fa-magnet" class="fa fa-magnet icon iconfont"></i></li>
		<li><i id="fa fa-chevron-up" class="fa fa-chevron-up icon iconfont"></i></li>
		<li><i id="fa fa-chevron-down" class="fa fa-chevron-down icon iconfont"></i></li>
		<li><i id="fa fa-retweet" class="fa fa-retweet icon iconfont"></i></li>
		<li><i id="fa fa-shopping-cart" class="fa fa-shopping-cart icon iconfont"></i></li>
		<li><i id="fa fa-folder" class="fa fa-folder icon iconfont"></i></li>
		<li><i id="fa fa-folder-open" class="fa fa-folder-open icon iconfont"></i></li>
		<li><i id="fa fa-arrows-v" class="fa fa-arrows-v icon iconfont"></i></li>
		<li><i id="fa fa-arrows-h" class="fa fa-arrows-h icon iconfont"></i></li>
		<li><i id="fa fa-twitter-square" class="fa fa-twitter-square icon iconfont"></i></li>
		<li><i id="fa fa-facebook-square" class="fa fa-facebook-square icon iconfont"></i></li>
		<li><i id="fa fa-camera-retro" class="fa fa-camera-retro icon iconfont"></i></li>
		<li><i id="fa fa-key" class="fa fa-key icon iconfont"></i></li>
		<li><i id="fa fa-comments" class="fa fa-comments icon iconfont"></i></li>
		<li><i id="fa fa-thumbs-o-up" class="fa fa-thumbs-o-up icon iconfont"></i></li>
		<li><i id="fa fa-thumbs-o-down" class="fa fa-thumbs-o-down icon iconfont"></i></li>
		<li><i id="fa fa-star-half" class="fa fa-star-half icon iconfont"></i></li>
		<li><i id="fa fa-heart-o" class="fa fa-heart-o icon iconfont"></i></li>
		<li><i id="fa fa-sign-out" class="fa fa-sign-out icon iconfont"></i></li>
		<li><i id="fa fa-linkedin-square" class="fa fa-linkedin-square icon iconfont"></i></li>
		<li><i id="fa fa-thumb-tack" class="fa fa-thumb-tack icon iconfont"></i></li>
		<li><i id="fa fa-external-link" class="fa fa-external-link icon iconfont"></i></li>
		<li><i id="fa fa-sign-in" class="fa fa-sign-in icon iconfont"></i></li>
		<li><i id="fa fa-trophy" class="fa fa-trophy icon iconfont"></i></li>
		<li><i id="fa fa-github-square" class="fa fa-github-square icon iconfont"></i></li>
		<li><i id="fa fa-upload" class="fa fa-upload icon iconfont"></i></li>
		<li><i id="fa fa-lemon-o" class="fa fa-lemon-o icon iconfont"></i></li>
		<li><i id="fa fa-phone" class="fa fa-phone icon iconfont"></i></li>
		<li><i id="fa fa-square-o" class="fa fa-square-o icon iconfont"></i></li>
		<li><i id="fa fa-bookmark-o" class="fa fa-bookmark-o icon iconfont"></i></li>
		<li><i id="fa fa-phone-square" class="fa fa-phone-square icon iconfont"></i></li>
		<li><i id="fa fa-twitter" class="fa fa-twitter icon iconfont"></i></li>
		<li><i id="fa fa-github" class="fa fa-github icon iconfont"></i></li>
		<li><i id="fa fa-unlock" class="fa fa-unlock icon iconfont"></i></li>
		<li><i id="fa fa-credit-card" class="fa fa-credit-card icon iconfont"></i></li>
		<li><i id="fa fa-hdd-o" class="fa fa-hdd-o icon iconfont"></i></li>
		<li><i id="fa fa-bullhorn" class="fa fa-bullhorn icon iconfont"></i></li>
		<li><i id="fa fa-bell" class="fa fa-bell icon iconfont"></i></li>
		<li><i id="fa fa-certificate" class="fa fa-certificate icon iconfont"></i></li>
		<li><i id="fa fa-hand-o-right" class="fa fa-hand-o-right icon iconfont"></i></li>
		<li><i id="fa fa-hand-o-left" class="fa fa-hand-o-left icon iconfont"></i></li>
		<li><i id="fa fa-hand-o-up" class="fa fa-hand-o-up icon iconfont"></i></li>
		<li><i id="fa fa-hand-o-down" class="fa fa-hand-o-down icon iconfont"></i></li>
		<li><i id="fa fa-arrow-circle-left" class="fa fa-arrow-circle-left icon iconfont"></i></li>
		<li><i id="fa fa-arrow-circle-right" class="fa fa-arrow-circle-right icon iconfont"></i></li>
		<li><i id="fa fa-arrow-circle-up" class="fa fa-arrow-circle-up icon iconfont"></i></li>
		<li><i id="fa fa-arrow-circle-down" class="fa fa-arrow-circle-down icon iconfont"></i></li>
		<li><i id="fa fa-globe" class="fa fa-globe icon iconfont"></i></li>
		<li><i id="fa fa-wrench" class="fa fa-wrench icon iconfont"></i></li>
		<li><i id="fa fa-tasks" class="fa fa-tasks icon iconfont"></i></li>
		<li><i id="fa fa-filter" class="fa fa-filter icon iconfont"></i></li>
		<li><i id="fa fa-briefcase" class="fa fa-briefcase icon iconfont"></i></li>
		<li><i id="fa fa-arrows-alt" class="fa fa-arrows-alt icon iconfont"></i></li>
		<li><i id="fa fa-cloud" class="fa fa-cloud icon iconfont"></i></li>
		<li><i id="fa fa-flask" class="fa fa-flask icon iconfont"></i></li>
		<li><i id="fa fa-paperclip" class="fa fa-paperclip icon iconfont"></i></li>
		<li><i id="fa fa-square" class="fa fa-square icon iconfont"></i></li>
		<li><i id="fa fa-list-ul" class="fa fa-list-ul icon iconfont"></i></li>
		<li><i id="fa fa-list-ol" class="fa fa-list-ol icon iconfont"></i></li>
		<li><i id="fa fa-strikethrough" class="fa fa-strikethrough icon iconfont"></i></li>
		<li><i id="fa fa-underline" class="fa fa-underline icon iconfont"></i></li>
		<li><i id="fa fa-table" class="fa fa-table icon iconfont"></i></li>
		<li><i id="fa fa-magic" class="fa fa-magic icon iconfont"></i></li>
		<li><i id="fa fa-truck" class="fa fa-truck icon iconfont"></i></li>
		<li><i id="fa fa-pinterest" class="fa fa-pinterest icon iconfont"></i></li>
		<li><i id="fa fa-pinterest-square" class="fa fa-pinterest-square icon iconfont"></i></li>
		<li><i id="fa fa-google-plus-square" class="fa fa-google-plus-square icon iconfont"></i></li>
		<li><i id="fa fa-google-plus" class="fa fa-google-plus icon iconfont"></i></li>
		<li><i id="fa fa-money" class="fa fa-money icon iconfont"></i></li>
		<li><i id="fa fa-caret-down" class="fa fa-caret-down icon iconfont"></i></li>
		<li><i id="fa fa-caret-up" class="fa fa-caret-up icon iconfont"></i></li>
		<li><i id="fa fa-caret-left" class="fa fa-caret-left icon iconfont"></i></li>
		<li><i id="fa fa-caret-right" class="fa fa-caret-right icon iconfont"></i></li>
		<li><i id="fa fa-columns" class="fa fa-columns icon iconfont"></i></li>
		<li><i id="fa fa-envelope" class="fa fa-envelope icon iconfont"></i></li>
		<li><i id="fa fa-linkedin" class="fa fa-linkedin icon iconfont"></i></li>
		<li><i id="fa fa-comment-o" class="fa fa-comment-o icon iconfont"></i></li>
		<li><i id="fa fa-comments-o" class="fa fa-comments-o icon iconfont"></i></li>
		<li><i id="fa fa-sitemap" class="fa fa-sitemap icon iconfont"></i></li>
		<li><i id="fa fa-umbrella" class="fa fa-umbrella icon iconfont"></i></li>
		<li><i id="fa fa-lightbulb-o" class="fa fa-lightbulb-o icon iconfont"></i></li>
		<li><i id="fa fa-exchange" class="fa fa-exchange icon iconfont"></i></li>
		<li><i id="fa fa-cloud-download" class="fa fa-cloud-download icon iconfont"></i></li>
		<li><i id="fa fa-cloud-upload" class="fa fa-cloud-upload icon iconfont"></i></li>
		<li><i id="fa fa-user-md" class="fa fa-user-md icon iconfont"></i></li>
		<li><i id="fa fa-stethoscope" class="fa fa-stethoscope icon iconfont"></i></li>
		<li><i id="fa fa-suitcase" class="fa fa-suitcase icon iconfont"></i></li>
		<li><i id="fa fa-bell-o" class="fa fa-bell-o icon iconfont"></i></li>
		<li><i id="fa fa-coffee" class="fa fa-coffee icon iconfont"></i></li>
		<li><i id="fa fa-cutlery" class="fa fa-cutlery icon iconfont"></i></li>
		<li><i id="fa fa-file-text-o" class="fa fa-file-text-o icon iconfont"></i></li>
		<li><i id="fa fa-building-o" class="fa fa-building-o icon iconfont"></i></li>
		<li><i id="fa fa-hospital-o" class="fa fa-hospital-o icon iconfont"></i></li>
		<li><i id="fa fa-ambulance" class="fa fa-ambulance icon iconfont"></i></li>
		<li><i id="fa fa-medkit" class="fa fa-medkit icon iconfont"></i></li>
		<li><i id="fa fa-fighter-jet" class="fa fa-fighter-jet icon iconfont"></i></li>
		<li><i id="fa fa-beer" class="fa fa-beer icon iconfont"></i></li>
		<li><i id="fa fa-h-square" class="fa fa-h-square icon iconfont"></i></li>
		<li><i id="fa fa-plus-square" class="fa fa-plus-square icon iconfont"></i></li>
		<li><i id="fa fa-angle-double-left" class="fa fa-angle-double-left icon iconfont"></i></li>
		<li><i id="fa fa-angle-double-right" class="fa fa-angle-double-right icon iconfont"></i></li>
		<li><i id="fa fa-angle-double-up" class="fa fa-angle-double-up icon iconfont"></i></li>
		<li><i id="fa fa-angle-double-down" class="fa fa-angle-double-down icon iconfont"></i></li>
		<li><i id="fa fa-angle-left" class="fa fa-angle-left icon iconfont"></i></li>
		<li><i id="fa fa-angle-right" class="fa fa-angle-right icon iconfont"></i></li>
		<li><i id="fa fa-angle-up" class="fa fa-angle-up icon iconfont"></i></li>
		<li><i id="fa fa-angle-down" class="fa fa-angle-down icon iconfont"></i></li>
		<li><i id="fa fa-desktop" class="fa fa-desktop icon iconfont"></i></li>
		<li><i id="fa fa-laptop" class="fa fa-laptop icon iconfont"></i></li>
		<li><i id="fa fa-tablet" class="fa fa-tablet icon iconfont"></i></li>
		<li><i id="fa fa-circle-o" class="fa fa-circle-o icon iconfont"></i></li>
		<li><i id="fa fa-quote-left" class="fa fa-quote-left icon iconfont"></i></li>
		<li><i id="fa fa-quote-right" class="fa fa-quote-right icon iconfont"></i></li>
		<li><i id="fa fa-spinner" class="fa fa-spinner icon iconfont"></i></li>
		<li><i id="fa fa-circle" class="fa fa-circle icon iconfont"></i></li>
		<li><i id="fa fa-github-alt" class="fa fa-github-alt icon iconfont"></i></li>
		<li><i id="fa fa-folder-o" class="fa fa-folder-o icon iconfont"></i></li>
		<li><i id="fa fa-folder-open-o" class="fa fa-folder-open-o icon iconfont"></i></li>
		<li><i id="fa fa-smile-o" class="fa fa-smile-o icon iconfont"></i></li>
		<li><i id="fa fa-frown-o" class="fa fa-frown-o icon iconfont"></i></li>
		<li><i id="fa fa-meh-o" class="fa fa-meh-o icon iconfont"></i></li>
		<li><i id="fa fa-gamepad" class="fa fa-gamepad icon iconfont"></i></li>
		<li><i id="fa fa-keyboard-o" class="fa fa-keyboard-o icon iconfont"></i></li>
		<li><i id="fa fa-flag-o" class="fa fa-flag-o icon iconfont"></i></li>
		<li><i id="fa fa-flag-checkered" class="fa fa-flag-checkered icon iconfont"></i></li>
		<li><i id="fa fa-terminal" class="fa fa-terminal icon iconfont"></i></li>
		<li><i id="fa fa-code" class="fa fa-code icon iconfont"></i></li>
		<li><i id="fa fa-location-arrow" class="fa fa-location-arrow icon iconfont"></i></li>
		<li><i id="fa fa-crop" class="fa fa-crop icon iconfont"></i></li>
		<li><i id="fa fa-code-fork" class="fa fa-code-fork icon iconfont"></i></li>
		<li><i id="fa fa-question" class="fa fa-question icon iconfont"></i></li>
		<li><i id="fa fa-info" class="fa fa-info icon iconfont"></i></li>
		<li><i id="fa fa-exclamation" class="fa fa-exclamation icon iconfont"></i></li>
		<li><i id="fa fa-superscript" class="fa fa-superscript icon iconfont"></i></li>
		<li><i id="fa fa-subscript" class="fa fa-subscript icon iconfont"></i></li>
		<li><i id="fa fa-eraser" class="fa fa-eraser icon iconfont"></i></li>
		<li><i id="fa fa-puzzle-piece" class="fa fa-puzzle-piece icon iconfont"></i></li>
		<li><i id="fa fa-microphone" class="fa fa-microphone icon iconfont"></i></li>
		<li><i id="fa fa-microphone-slash" class="fa fa-microphone-slash icon iconfont"></i></li>
		<li><i id="fa fa-shield" class="fa fa-shield icon iconfont"></i></li>
		<li><i id="fa fa-calendar-o" class="fa fa-calendar-o icon iconfont"></i></li>
		<li><i id="fa fa-fire-extinguisher" class="fa fa-fire-extinguisher icon iconfont"></i></li>
		<li><i id="fa fa-rocket" class="fa fa-rocket icon iconfont"></i></li>
		<li><i id="fa fa-maxcdn" class="fa fa-maxcdn icon iconfont"></i></li>
		<li><i id="fa fa-chevron-circle-left" class="fa fa-chevron-circle-left icon iconfont"></i></li>
		<li><i id="fa fa-chevron-circle-right" class="fa fa-chevron-circle-right icon iconfont"></i></li>
		<li><i id="fa fa-chevron-circle-up" class="fa fa-chevron-circle-up icon iconfont"></i></li>
		<li><i id="fa fa-chevron-circle-down" class="fa fa-chevron-circle-down icon iconfont"></i></li>
		<li><i id="fa fa-html5" class="fa fa-html5 icon iconfont"></i></li>
		<li><i id="fa fa-css3" class="fa fa-css3 icon iconfont"></i></li>
		<li><i id="fa fa-anchor" class="fa fa-anchor icon iconfont"></i></li>
		<li><i id="fa fa-unlock-alt" class="fa fa-unlock-alt icon iconfont"></i></li>
		<li><i id="fa fa-bullseye" class="fa fa-bullseye icon iconfont"></i></li>
		<li><i id="fa fa-ellipsis-h" class="fa fa-ellipsis-h icon iconfont"></i></li>
		<li><i id="fa fa-ellipsis-v" class="fa fa-ellipsis-v icon iconfont"></i></li>
		<li><i id="fa fa-rss-square" class="fa fa-rss-square icon iconfont"></i></li>
		<li><i id="fa fa-play-circle" class="fa fa-play-circle icon iconfont"></i></li>
		<li><i id="fa fa-ticket" class="fa fa-ticket icon iconfont"></i></li>
		<li><i id="fa fa-minus-square" class="fa fa-minus-square icon iconfont"></i></li>
		<li><i id="fa fa-minus-square-o" class="fa fa-minus-square-o icon iconfont"></i></li>
		<li><i id="fa fa-level-up" class="fa fa-level-up icon iconfont"></i></li>
		<li><i id="fa fa-level-down" class="fa fa-level-down icon iconfont"></i></li>
		<li><i id="fa fa-check-square" class="fa fa-check-square icon iconfont"></i></li>
		<li><i id="fa fa-pencil-square" class="fa fa-pencil-square icon iconfont"></i></li>
		<li><i id="fa fa-external-link-square" class="fa fa-external-link-square icon iconfont"></i></li>
		<li><i id="fa fa-share-square" class="fa fa-share-square icon iconfont"></i></li>
		<li><i id="fa fa-compass" class="fa fa-compass icon iconfont"></i></li>
		<li><i id="fa fa-gbp" class="fa fa-gbp icon iconfont"></i></li>
		<li><i id="fa fa-file" class="fa fa-file icon iconfont"></i></li>
		<li><i id="fa fa-file-text" class="fa fa-file-text icon iconfont"></i></li>
		<li><i id="fa fa-sort-alpha-asc" class="fa fa-sort-alpha-asc icon iconfont"></i></li>
		<li><i id="fa fa-sort-alpha-desc" class="fa fa-sort-alpha-desc icon iconfont"></i></li>
		<li><i id="fa fa-sort-amount-asc" class="fa fa-sort-amount-asc icon iconfont"></i></li>
		<li><i id="fa fa-sort-amount-desc" class="fa fa-sort-amount-desc icon iconfont"></i></li>
		<li><i id="fa fa-sort-numeric-asc" class="fa fa-sort-numeric-asc icon iconfont"></i></li>
		<li><i id="fa fa-sort-numeric-desc" class="fa fa-sort-numeric-desc icon iconfont"></i></li>
		<li><i id="fa fa-thumbs-up" class="fa fa-thumbs-up icon iconfont"></i></li>
		<li><i id="fa fa-thumbs-down" class="fa fa-thumbs-down icon iconfont"></i></li>
		<li><i id="fa fa-youtube-square" class="fa fa-youtube-square icon iconfont"></i></li>
		<li><i id="fa fa-youtube" class="fa fa-youtube icon iconfont"></i></li>
		<li><i id="fa fa-xing" class="fa fa-xing icon iconfont"></i></li>
		<li><i id="fa fa-xing-square" class="fa fa-xing-square icon iconfont"></i></li>
		<li><i id="fa fa-youtube-play" class="fa fa-youtube-play icon iconfont"></i></li>
		<li><i id="fa fa-dropbox" class="fa fa-dropbox icon iconfont"></i></li>
		<li><i id="fa fa-stack-overflow" class="fa fa-stack-overflow icon iconfont"></i></li>
		<li><i id="fa fa-instagram" class="fa fa-instagram icon iconfont"></i></li>
		<li><i id="fa fa-flickr" class="fa fa-flickr icon iconfont"></i></li>
		<li><i id="fa fa-adn" class="fa fa-adn icon iconfont"></i></li>
		<li><i id="fa fa-bitbucket" class="fa fa-bitbucket icon iconfont"></i></li>
		<li><i id="fa fa-bitbucket-square" class="fa fa-bitbucket-square icon iconfont"></i></li>
		<li><i id="fa fa-tumblr" class="fa fa-tumblr icon iconfont"></i></li>
		<li><i id="fa fa-tumblr-square" class="fa fa-tumblr-square icon iconfont"></i></li>
		<li><i id="fa fa-long-arrow-down" class="fa fa-long-arrow-down icon iconfont"></i></li>
		<li><i id="fa fa-long-arrow-up" class="fa fa-long-arrow-up icon iconfont"></i></li>
		<li><i id="fa fa-long-arrow-left" class="fa fa-long-arrow-left icon iconfont"></i></li>
		<li><i id="fa fa-long-arrow-right" class="fa fa-long-arrow-right icon iconfont"></i></li>
		<li><i id="fa fa-apple" class="fa fa-apple icon iconfont"></i></li>
		<li><i id="fa fa-windows" class="fa fa-windows icon iconfont"></i></li>
		<li><i id="fa fa-android" class="fa fa-android icon iconfont"></i></li>
		<li><i id="fa fa-linux" class="fa fa-linux icon iconfont"></i></li>
		<li><i id="fa fa-dribbble" class="fa fa-dribbble icon iconfont"></i></li>
		<li><i id="fa fa-skype" class="fa fa-skype icon iconfont"></i></li>
		<li><i id="fa fa-foursquare" class="fa fa-foursquare icon iconfont"></i></li>
		<li><i id="fa fa-trello" class="fa fa-trello icon iconfont"></i></li>
		<li><i id="fa fa-female" class="fa fa-female icon iconfont"></i></li>
		<li><i id="fa fa-male" class="fa fa-male icon iconfont"></i></li>
		<li><i id="fa fa-sun-o" class="fa fa-sun-o icon iconfont"></i></li>
		<li><i id="fa fa-moon-o" class="fa fa-moon-o icon iconfont"></i></li>
		<li><i id="fa fa-archive" class="fa fa-archive icon iconfont"></i></li>
		<li><i id="fa fa-bug" class="fa fa-bug icon iconfont"></i></li>
		<li><i id="fa fa-vk" class="fa fa-vk icon iconfont"></i></li>
		<li><i id="fa fa-weibo" class="fa fa-weibo icon iconfont"></i></li>
		<li><i id="fa fa-renren" class="fa fa-renren icon iconfont"></i></li>
		<li><i id="fa fa-pagelines" class="fa fa-pagelines icon iconfont"></i></li>
		<li><i id="fa fa-stack-exchange" class="fa fa-stack-exchange icon iconfont"></i></li>
		<li><i id="fa fa-arrow-circle-o-right" class="fa fa-arrow-circle-o-right icon iconfont"></i></li>
		<li><i id="fa fa-arrow-circle-o-left" class="fa fa-arrow-circle-o-left icon iconfont"></i></li>
		<li><i id="fa fa-dot-circle-o" class="fa fa-dot-circle-o icon iconfont"></i></li>
		<li><i id="fa fa-wheelchair" class="fa fa-wheelchair icon iconfont"></i></li>
		<li><i id="fa fa-vimeo-square" class="fa fa-vimeo-square icon iconfont"></i></li>
		<li><i id="fa fa-plus-square-o" class="fa fa-plus-square-o icon iconfont"></i></li>
		<li><i id="fa fa-space-shuttle" class="fa fa-space-shuttle icon iconfont"></i></li>
		<li><i id="fa fa-slack" class="fa fa-slack icon iconfont"></i></li>
		<li><i id="fa fa-envelope-square" class="fa fa-envelope-square icon iconfont"></i></li>
		<li><i id="fa fa-wordpress" class="fa fa-wordpress icon iconfont"></i></li>
		<li><i id="fa fa-openid" class="fa fa-openid icon iconfont"></i></li>
		<li><i id="fa fa-yahoo" class="fa fa-yahoo icon iconfont"></i></li>
		<li><i id="fa fa-google" class="fa fa-google icon iconfont"></i></li>
		<li><i id="fa fa-reddit" class="fa fa-reddit icon iconfont"></i></li>
		<li><i id="fa fa-reddit-square" class="fa fa-reddit-square icon iconfont"></i></li>
		<li><i id="fa fa-stumbleupon-circle" class="fa fa-stumbleupon-circle icon iconfont"></i></li>
		<li><i id="fa fa-stumbleupon" class="fa fa-stumbleupon icon iconfont"></i></li>
		<li><i id="fa fa-delicious" class="fa fa-delicious icon iconfont"></i></li>
		<li><i id="fa fa-digg" class="fa fa-digg icon iconfont"></i></li>
		<li><i id="fa fa-pied-piper" class="fa fa-pied-piper icon iconfont"></i></li>
		<li><i id="fa fa-pied-piper-alt" class="fa fa-pied-piper-alt icon iconfont"></i></li>
		<li><i id="fa fa-drupal" class="fa fa-drupal icon iconfont"></i></li>
		<li><i id="fa fa-joomla" class="fa fa-joomla icon iconfont"></i></li>
		<li><i id="fa fa-language" class="fa fa-language icon iconfont"></i></li>
		<li><i id="fa fa-fax" class="fa fa-fax icon iconfont"></i></li>
		<li><i id="fa fa-building" class="fa fa-building icon iconfont"></i></li>
		<li><i id="fa fa-child" class="fa fa-child icon iconfont"></i></li>
		<li><i id="fa fa-paw" class="fa fa-paw icon iconfont"></i></li>
		<li><i id="fa fa-spoon" class="fa fa-spoon icon iconfont"></i></li>
		<li><i id="fa fa-cube" class="fa fa-cube icon iconfont"></i></li>
		<li><i id="fa fa-cubes" class="fa fa-cubes icon iconfont"></i></li>
		<li><i id="fa fa-behance" class="fa fa-behance icon iconfont"></i></li>
		<li><i id="fa fa-behance-square" class="fa fa-behance-square icon iconfont"></i></li>
		<li><i id="fa fa-steam" class="fa fa-steam icon iconfont"></i></li>
		<li><i id="fa fa-steam-square" class="fa fa-steam-square icon iconfont"></i></li>
		<li><i id="fa fa-recycle" class="fa fa-recycle icon iconfont"></i></li>
		<li><i id="fa fa-tree" class="fa fa-tree icon iconfont"></i></li>
		<li><i id="fa fa-spotify" class="fa fa-spotify icon iconfont"></i></li>
		<li><i id="fa fa-deviantart" class="fa fa-deviantart icon iconfont"></i></li>
		<li><i id="fa fa-soundcloud" class="fa fa-soundcloud icon iconfont"></i></li>
		<li><i id="fa fa-database" class="fa fa-database icon iconfont"></i></li>
		<li><i id="fa fa-file-pdf-o" class="fa fa-file-pdf-o icon iconfont"></i></li>
		<li><i id="fa fa-file-word-o" class="fa fa-file-word-o icon iconfont"></i></li>
		<li><i id="fa fa-file-excel-o" class="fa fa-file-excel-o icon iconfont"></i></li>
		<li><i id="fa fa-file-powerpoint-o" class="fa fa-file-powerpoint-o icon iconfont"></i></li>
		<li><i id="fa fa-file-code-o" class="fa fa-file-code-o icon iconfont"></i></li>
		<li><i id="fa fa-vine" class="fa fa-vine icon iconfont"></i></li>
		<li><i id="fa fa-codepen" class="fa fa-codepen icon iconfont"></i></li>
		<li><i id="fa fa-jsfiddle" class="fa fa-jsfiddle icon iconfont"></i></li>
		<li><i id="fa fa-circle-o-notch" class="fa fa-circle-o-notch icon iconfont"></i></li>
		<li><i id="fa fa-git-square" class="fa fa-git-square icon iconfont"></i></li>
		<li><i id="fa fa-git" class="fa fa-git icon iconfont"></i></li>
		<li><i id="fa fa-tencent-weibo" class="fa fa-tencent-weibo icon iconfont"></i></li>
		<li><i id="fa fa-qq" class="fa fa-qq icon iconfont"></i></li>
		<li><i id="fa fa-history" class="fa fa-history icon iconfont"></i></li>
		<li><i id="fa fa-circle-thin" class="fa fa-circle-thin icon iconfont"></i></li>
		<li><i id="fa fa-header" class="fa fa-header icon iconfont"></i></li>
		<li><i id="fa fa-paragraph" class="fa fa-paragraph icon iconfont"></i></li>
		<li><i id="fa fa-sliders" class="fa fa-sliders icon iconfont"></i></li>
		<li><i id="fa fa-share-alt" class="fa fa-share-alt icon iconfont"></i></li>
		<li><i id="fa fa-share-alt-square" class="fa fa-share-alt-square icon iconfont"></i></li>
		<li><i id="fa fa-bomb" class="fa fa-bomb icon iconfont"></i></li>
		<li><i id="fa fa-tty" class="fa fa-tty icon iconfont"></i></li>
		<li><i id="fa fa-binoculars" class="fa fa-binoculars icon iconfont"></i></li>
		<li><i id="fa fa-plug" class="fa fa-plug icon iconfont"></i></li>
		<li><i id="fa fa-slideshare" class="fa fa-slideshare icon iconfont"></i></li>
		<li><i id="fa fa-twitch" class="fa fa-twitch icon iconfont"></i></li>
		<li><i id="fa fa-yelp" class="fa fa-yelp icon iconfont"></i></li>
		<li><i id="fa fa-newspaper-o" class="fa fa-newspaper-o icon iconfont"></i></li>
		<li><i id="fa fa-wifi" class="fa fa-wifi icon iconfont"></i></li>
		<li><i id="fa fa-calculator" class="fa fa-calculator icon iconfont"></i></li>
		<li><i id="fa fa-paypal" class="fa fa-paypal icon iconfont"></i></li>
		<li><i id="fa fa-google-wallet" class="fa fa-google-wallet icon iconfont"></i></li>
		<li><i id="fa fa-cc-visa" class="fa fa-cc-visa icon iconfont"></i></li>
		<li><i id="fa fa-cc-mastercard" class="fa fa-cc-mastercard icon iconfont"></i></li>
		<li><i id="fa fa-cc-discover" class="fa fa-cc-discover icon iconfont"></i></li>
		<li><i id="fa fa-cc-amex" class="fa fa-cc-amex icon iconfont"></i></li>
		<li><i id="fa fa-cc-paypal" class="fa fa-cc-paypal icon iconfont"></i></li>
		<li><i id="fa fa-cc-stripe" class="fa fa-cc-stripe icon iconfont"></i></li>
		<li><i id="fa fa-bell-slash" class="fa fa-bell-slash icon iconfont"></i></li>
		<li><i id="fa fa-bell-slash-o" class="fa fa-bell-slash-o icon iconfont"></i></li>
		<li><i id="fa fa-trash" class="fa fa-trash icon iconfont"></i></li>
		<li><i id="fa fa-copyright" class="fa fa-copyright icon iconfont"></i></li>
		<li><i id="fa fa-at" class="fa fa-at icon iconfont"></i></li>
		<li><i id="fa fa-eyedropper" class="fa fa-eyedropper icon iconfont"></i></li>
		<li><i id="fa fa-paint-brush" class="fa fa-paint-brush icon iconfont"></i></li>
		<li><i id="fa fa-birthday-cake" class="fa fa-birthday-cake icon iconfont"></i></li>
		<li><i id="fa fa-area-chart" class="fa fa-area-chart icon iconfont"></i></li>
		<li><i id="fa fa-pie-chart" class="fa fa-pie-chart icon iconfont"></i></li>
		<li><i id="fa fa-line-chart" class="fa fa-line-chart icon iconfont"></i></li>
		<li><i id="fa fa-lastfm" class="fa fa-lastfm icon iconfont"></i></li>
		<li><i id="fa fa-lastfm-square" class="fa fa-lastfm-square icon iconfont"></i></li>
		<li><i id="fa fa-toggle-off" class="fa fa-toggle-off icon iconfont"></i></li>
		<li><i id="fa fa-toggle-on" class="fa fa-toggle-on icon iconfont"></i></li>
		<li><i id="fa fa-bicycle" class="fa fa-bicycle icon iconfont"></i></li>
		<li><i id="fa fa-bus" class="fa fa-bus icon iconfont"></i></li>
		<li><i id="fa fa-ioxhost" class="fa fa-ioxhost icon iconfont"></i></li>
		<li><i id="fa fa-angellist" class="fa fa-angellist icon iconfont"></i></li>
		<li><i id="fa fa-cc" class="fa fa-cc icon iconfont"></i></li>
		<li><i id="fa fa-meanpath" class="fa fa-meanpath icon iconfont"></i></li>
		<li><i id="fa fa-buysellads" class="fa fa-buysellads icon iconfont"></i></li>
		<li><i id="fa fa-connectdevelop" class="fa fa-connectdevelop icon iconfont"></i></li>
		<li><i id="fa fa-dashcube" class="fa fa-dashcube icon iconfont"></i></li>
		<li><i id="fa fa-forumbee" class="fa fa-forumbee icon iconfont"></i></li>
		<li><i id="fa fa-leanpub" class="fa fa-leanpub icon iconfont"></i></li>
		<li><i id="fa fa-sellsy" class="fa fa-sellsy icon iconfont"></i></li>
		<li><i id="fa fa-shirtsinbulk" class="fa fa-shirtsinbulk icon iconfont"></i></li>
		<li><i id="fa fa-simplybuilt" class="fa fa-simplybuilt icon iconfont"></i></li>
		<li><i id="fa fa-skyatlas" class="fa fa-skyatlas icon iconfont"></i></li>
		<li><i id="fa fa-cart-plus" class="fa fa-cart-plus icon iconfont"></i></li>
		<li><i id="fa fa-cart-arrow-down" class="fa fa-cart-arrow-down icon iconfont"></i></li>
		<li><i id="fa fa-diamond" class="fa fa-diamond icon iconfont"></i></li>
		<li><i id="fa fa-ship" class="fa fa-ship icon iconfont"></i></li>
		<li><i id="fa fa-user-secret" class="fa fa-user-secret icon iconfont"></i></li>
		<li><i id="fa fa-motorcycle" class="fa fa-motorcycle icon iconfont"></i></li>
		<li><i id="fa fa-street-view" class="fa fa-street-view icon iconfont"></i></li>
		<li><i id="fa fa-heartbeat" class="fa fa-heartbeat icon iconfont"></i></li>
		<li><i id="fa fa-venus" class="fa fa-venus icon iconfont"></i></li>
		<li><i id="fa fa-mars" class="fa fa-mars icon iconfont"></i></li>
		<li><i id="fa fa-mercury" class="fa fa-mercury icon iconfont"></i></li>
		<li><i id="fa fa-transgender-alt" class="fa fa-transgender-alt icon iconfont"></i></li>
		<li><i id="fa fa-venus-double" class="fa fa-venus-double icon iconfont"></i></li>
		<li><i id="fa fa-mars-double" class="fa fa-mars-double icon iconfont"></i></li>
		<li><i id="fa fa-venus-mars" class="fa fa-venus-mars icon iconfont"></i></li>
		<li><i id="fa fa-mars-stroke" class="fa fa-mars-stroke icon iconfont"></i></li>
		<li><i id="fa fa-mars-stroke-v" class="fa fa-mars-stroke-v icon iconfont"></i></li>
		<li><i id="fa fa-mars-stroke-h" class="fa fa-mars-stroke-h icon iconfont"></i></li>
		<li><i id="fa fa-neuter" class="fa fa-neuter icon iconfont"></i></li>
		<li><i id="fa fa-genderless" class="fa fa-genderless icon iconfont"></i></li>
		<li><i id="fa fa-facebook-official" class="fa fa-facebook-official icon iconfont"></i></li>
		<li><i id="fa fa-pinterest-p" class="fa fa-pinterest-p icon iconfont"></i></li>
		<li><i id="fa fa-whatsapp" class="fa fa-whatsapp icon iconfont"></i></li>
		<li><i id="fa fa-server" class="fa fa-server icon iconfont"></i></li>
		<li><i id="fa fa-user-plus" class="fa fa-user-plus icon iconfont"></i></li>
		<li><i id="fa fa-user-times" class="fa fa-user-times icon iconfont"></i></li>
		<li><i id="fa fa-viacoin" class="fa fa-viacoin icon iconfont"></i></li>
		<li><i id="fa fa-train" class="fa fa-train icon iconfont"></i></li>
		<li><i id="fa fa-subway" class="fa fa-subway icon iconfont"></i></li>
		<li><i id="fa fa-medium" class="fa fa-medium icon iconfont"></i></li>
		<li><i id="fa fa-optin-monster" class="fa fa-optin-monster icon iconfont"></i></li>
		<li><i id="fa fa-opencart" class="fa fa-opencart icon iconfont"></i></li>
		<li><i id="fa fa-expeditedssl" class="fa fa-expeditedssl icon iconfont"></i></li>
		<li><i id="fa fa-mouse-pointer" class="fa fa-mouse-pointer icon iconfont"></i></li>
		<li><i id="fa fa-i-cursor" class="fa fa-i-cursor icon iconfont"></i></li>
		<li><i id="fa fa-object-group" class="fa fa-object-group icon iconfont"></i></li>
		<li><i id="fa fa-object-ungroup" class="fa fa-object-ungroup icon iconfont"></i></li>
		<li><i id="fa fa-sticky-note" class="fa fa-sticky-note icon iconfont"></i></li>
		<li><i id="fa fa-sticky-note-o" class="fa fa-sticky-note-o icon iconfont"></i></li>
		<li><i id="fa fa-cc-jcb" class="fa fa-cc-jcb icon iconfont"></i></li>
		<li><i id="fa fa-cc-diners-club" class="fa fa-cc-diners-club icon iconfont"></i></li>
		<li><i id="fa fa-clone" class="fa fa-clone icon iconfont"></i></li>
		<li><i id="fa fa-balance-scale" class="fa fa-balance-scale icon iconfont"></i></li>
		<li><i id="fa fa-hourglass-o" class="fa fa-hourglass-o icon iconfont"></i></li>
		<li><i id="fa fa-hourglass" class="fa fa-hourglass icon iconfont"></i></li>
		<li><i id="fa fa-hand-scissors-o" class="fa fa-hand-scissors-o icon iconfont"></i></li>
		<li><i id="fa fa-hand-lizard-o" class="fa fa-hand-lizard-o icon iconfont"></i></li>
		<li><i id="fa fa-hand-spock-o" class="fa fa-hand-spock-o icon iconfont"></i></li>
		<li><i id="fa fa-hand-pointer-o" class="fa fa-hand-pointer-o icon iconfont"></i></li>
		<li><i id="fa fa-hand-peace-o" class="fa fa-hand-peace-o icon iconfont"></i></li>
		<li><i id="fa fa-trademark" class="fa fa-trademark icon iconfont"></i></li>
		<li><i id="fa fa-registered" class="fa fa-registered icon iconfont"></i></li>
		<li><i id="fa fa-creative-commons" class="fa fa-creative-commons icon iconfont"></i></li>
		<li><i id="fa fa-gg" class="fa fa-gg icon iconfont"></i></li>
		<li><i id="fa fa-gg-circle" class="fa fa-gg-circle icon iconfont"></i></li>
		<li><i id="fa fa-tripadvisor" class="fa fa-tripadvisor icon iconfont"></i></li>
		<li><i id="fa fa-odnoklassniki" class="fa fa-odnoklassniki icon iconfont"></i></li>
		<li><i id="fa fa-odnoklassniki-square" class="fa fa-odnoklassniki-square icon iconfont"></i></li>
		<li><i id="fa fa-get-pocket" class="fa fa-get-pocket icon iconfont"></i></li>
		<li><i id="fa fa-wikipedia-w" class="fa fa-wikipedia-w icon iconfont"></i></li>
		<li><i id="fa fa-safari" class="fa fa-safari icon iconfont"></i></li>
		<li><i id="fa fa-chrome" class="fa fa-chrome icon iconfont"></i></li>
		<li><i id="fa fa-firefox" class="fa fa-firefox icon iconfont"></i></li>
		<li><i id="fa fa-opera" class="fa fa-opera icon iconfont"></i></li>
		<li><i id="fa fa-internet-explorer" class="fa fa-internet-explorer icon iconfont"></i></li>
		<li><i id="fa fa-contao" class="fa fa-contao icon iconfont"></i></li>
		<li><i id="fa fa-500px" class="fa fa-500px icon iconfont"></i></li>
		<li><i id="fa fa-amazon" class="fa fa-amazon icon iconfont"></i></li>
		<li><i id="fa fa-calendar-plus-o" class="fa fa-calendar-plus-o icon iconfont"></i></li>
		<li><i id="fa fa-calendar-minus-o" class="fa fa-calendar-minus-o icon iconfont"></i></li>
		<li><i id="fa fa-calendar-times-o" class="fa fa-calendar-times-o icon iconfont"></i></li>
		<li><i id="fa fa-calendar-check-o" class="fa fa-calendar-check-o icon iconfont"></i></li>
		<li><i id="fa fa-industry" class="fa fa-industry icon iconfont"></i></li>
		<li><i id="fa fa-map-pin" class="fa fa-map-pin icon iconfont"></i></li>
		<li><i id="fa fa-map-signs" class="fa fa-map-signs icon iconfont"></i></li>
		<li><i id="fa fa-map-o" class="fa fa-map-o icon iconfont"></i></li>
		<li><i id="fa fa-map" class="fa fa-map icon iconfont"></i></li>
		<li><i id="fa fa-commenting" class="fa fa-commenting icon iconfont"></i></li>
		<li><i id="fa fa-commenting-o" class="fa fa-commenting-o icon iconfont"></i></li>
		<li><i id="fa fa-houzz" class="fa fa-houzz icon iconfont"></i></li>
		<li><i id="fa fa-vimeo" class="fa fa-vimeo icon iconfont"></i></li>
		<li><i id="fa fa-black-tie" class="fa fa-black-tie icon iconfont"></i></li>
		<li><i id="fa fa-fonticons" class="fa fa-fonticons icon iconfont"></i></li>
	</ul>
</div>

<script type="text/javascript">
$("#icon_li i").click(function(){
	var obj = $(this);
	$("#icon").textbox('setValue', obj.attr("id"));
});
</script>